default:
    css:
        - /assets/dev/css/bootstrap.css
        - /assets/dev/css/style.css
    js:
        - /assets/dev/js/libs/angular.js
        - /assets/dev/js/libs/jquery.js
        - /assets/dev/js/libs/bootstrap.js
        - /assets/dev/js/app.js
        - /assets/dev/js/controllers/index.js
        - /assets/dev/js/controllers/register.js
